### ISSUE TITLE
GCP deployment using yaml file

### ISSUE THREAD

**Issue by praveen7557** [actions/gcloud#18]
I am trying to deploy my nodejs app to GCP App Engine using actions. I am using yaml file for the workflow. But I am getting this error when I deploy.

This is my yaml configuration.

```
name: Node CI
on: [push]
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install -g yarn
        yarn install
      env:
        CI: true
        MONGO_URI: ***********
        JWT_SECRET: **********
        JWT_EXPIRATION_MINUTES: 43200
        NODE_ENV: production
        JOB_TYPES: notifs
        FCM_SERVER_KEY: **********
    - name: Setup Google Cloud
      uses: actions/gcloud/auth@master
      env:
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
    - name: Delpoy to GCP
      uses: actions/gcloud/cli@master
      with:
        args: "gcloud app deploy --project trippy-7557"
```
