### ISSUE TITLE
Actions documentation on how to store secrets is broken

### ISSUE THREAD

**Issue by edkb** [actions/gcloud#21]
Hello, the link https://developer.github.com/actions/creating-workflows/storing-secrets/ is redirects to https://help.github.com/en/categories/automating-your-workflow-with-github-actions 
Also, I'm having trouble to correctly using secrets with the yaml syntax.
Would like to know what is wrong with the following workflow, having the content of the GCLOUD_AUTH beeing the return from the command` base64 ~/<account_id>.json`:
```
name: GCP Workflow
on: push
jobs:
  auth-and-deploy:
    name: GCP auth and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/gcloud/auth@master
        with:
           secrets: ${{secrets.GCLOUD_AUTH}}
      - uses: actions/gcloud/cli@master
        with:
          args: app deploy app.yaml
```
It returns the following error on the auth action: _ERROR: (gcloud.auth.activate-service-account) Could not read json file /github/home/gcloud.json: No JSON object could be decoded_

**Comment by gorkalaucirica** [comment]
It seems that actions are not passing secrets as env variables anymore but [auth entrypoint](https://github.com/actions/gcloud/blob/master/auth/entrypoint.sh) is trying to read the secret using that value.

Workaround: 

```
- name: "Authenticate in GCloud"
   uses: actions/gcloud/auth@master
   env:
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
```

**Comment by edkb** [comment]
Thank you @gorkalaucirica, it worked!
Also, it needs the project that can be set temporarily by the environment variable [CLOUDSDK_CORE_PROJECT]

Final action:
```
- uses: actions/gcloud/auth@master
   env:
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
        CLOUDSDK_CORE_PROJECT: ${{ secrets.GCLOUD_PROJECT_ID }}
```
