### ISSUE TITLE
Installing and using beta components

### ISSUE THREAD

**Issue by antony** [actions/gcloud#22]
It looks like if you want to use Google Cloud Run with this, you'd need to install the beta components:

```yaml
    - name: GCR Install Beta
      uses: actions/gcloud/cli@master
      with:
        args: components install beta --quiet
```

However if you then try to use them:

```yaml
    - name: GCR Deploy
      uses: actions/gcloud/cli@master
      with:
        args: beta run deploy --image $CONTAINER_NAME --platform managed
```

You will get the following error:

```bash
You do not currently have this command group installed.  Using it 
requires the installation of components: [beta]
```

and an automatic install, which will fail, since you can't pass `--quiet` to it.

I suppose that one good way to do this is to have a branch: `actions/gcloud@beta`. Other than that, there might be an issue with the action in that it isn't persisting the components once installed.
