### ISSUE TITLE
gcloud base for interaction with Google Storage (via gsutil)

### ISSUE THREAD

**Issue by vsoch** [actions/gcloud#5]
How feasible would it be to either create an actions/gsutil. or another folder here with the gcloud base (not gcloud-slim) so that the user of this action could also use gsutil? I'm putting together a workflow that will create a bucket, and then use gcloud builds to create a builder, build a container, and send to storage, and it's essential to have gsutil! I can put together some other GitHub Actions repository for this goal, but I think it would be best served (and found) with the official gcloud actions repository. Let me know if I can help by way of PR, etc., and I'd be glad to!

**Comment by shogomuranushi** [comment]
It may not be what you want,
You can do the same with Docker Image from CloudBuild (cloud-builders).

```
    steps:
    - uses: actions/checkout@v1
    - name: Setup Google Cloud
      uses: actions/gcloud/auth@master
      env:
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
    - name: GCP List Clusters
      uses: actions/gcloud/cli@master
      with:
        args: container clusters list
      env:
        CLOUDSDK_CORE_PROJECT: < project id >
    - name: GCS List Buckets
      uses: docker://gcr.io/cloud-builders/gsutil
      with:
        args: ls
      env:
        CLOUDSDK_CORE_PROJECT: < project id >
```

**Comment by jordankid93** [comment]
To build off of what @shogomuranushi  suggested (thanks btw), here is what I'm using to upload my CRA (create-react-app) project to my GCloud bucket (for those that may come across this in the future 👍🏽, it took me way to long to figure this out on my own ha)

```
name: CD

on:
  release:
    types: [published]

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v1
    
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 12
        
    - name: Install packages
      run: yarn install
      
    - name: Sanity linting
      run: yarn lint

    - name: Sanity tests
      run: CI=true yarn test

    - name: Build files
      run: yarn build
      
    - name: Setup Google Cloud
      uses: actions/gcloud/auth@master
      env:
        GCLOUD_AUTH: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      
    - name: Upload files
      uses: docker://gcr.io/cloud-builders/gsutil
      with:
        args: -m cp -r build/* gs://www.isaiahsmith.dev
      env:
        CLOUDSDK_CORE_PROJECT: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}
```

In theory you could prolly hardcode the project id (I'm not entirely sure thats sensitive but better safe than sorry?), but DEF keep your GOOGLE_APPLICATION_CREDENTIALS in secrets 🤙🏽

**Comment by jordankid93** [comment]
To build off of what @shogomuranushi suggested (thanks btw), here is what I'm using to upload my CRA (create-react-app) project to my GCloud bucket (for those that may come across this in the future 👍🏽, it took me way to long to figure this out on my own 😅)
```
name: CD

on:
  release:
    types: [published]

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v1
    
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 12
        
    - name: Install packages
      run: yarn install
      
    - name: Sanity linting
      run: yarn lint

    - name: Sanity tests
      run: CI=true yarn test

    - name: Build files
      run: yarn build
      
    - name: Setup Google Cloud
      uses: actions/gcloud/auth@master
      env:
        GCLOUD_AUTH: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      
    - name: Upload files
      uses: docker://gcr.io/cloud-builders/gsutil
      with:
        args: -m cp -r build/* < bucket link for gsutil >
      env:
        CLOUDSDK_CORE_PROJECT: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}
```
In theory you could prolly hardcode the project id and bucket link (I'm not entirely sure if that's sensitive but better safe than sorry?), but DEF keep your GOOGLE_APPLICATION_CREDENTIALS in secrets 🤙🏽

You can find your bucket's link for gsutil under the "Overview" tab of your bucket (should be _something_ like `gs://BUCKET_NAME_HERE`)
